from lista import Lista
archivos = Lista()
archivos.append('productos.xlsx')
archivos.append('actividad_proyecto_data.py')
archivos.append('lista.py')
archivos.append('prueba.py')
archivos.append('aeropuerto_data.py')
archivos.append('lista_circular.py')
archivos.append('README.md')
archivos.append('canciones')
archivos.append('lista_de.py')
archivos.append('StarWars')
archivos.append('canciones.py')
archivos.append('localdata.py')
archivos.append('starwars.data')
archivos.append('commitdata.py')
archivos.append('nombresdata.py')
archivos.append('starwars.py')
archivos.append('conjunto.py')
archivos.append('pokemondata.py')
archivos.append('starwarsdata.py')
archivos.append('LICENSE')
archivos.append('pokemondata.txt')
archivos.append('tp_lista.py')
archivos.append('list.rtf')
archivos.append('productos.csv')
archivos.append('Test.py')